spring:
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000 # будем писать 300 записей за раз
        order_inserts: true # вставлять записи в порядке их появления
    show-sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/Storage
    username: postgres
    password: 2133
    driver-class-name: org.postgresql.Driver
#  server:
#    port: 8443
#    ssl:
#      key-store: classpath:keystore.p12 # keytool -genkeypair -alias tomcat -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore src/main/resources/keystore.p12 -validity 3650
##      key-store-password: your_password
#      key-store-type: PKCS12
#      key-alias: tomcat